export function print(message);
export function floor(number);
export function round(number);
export function ceil(number);
export function random();
export function sqrt(number);
export function max(number1, number2);
export function min(number1, number2);
export function abs(number);
export function sign(number);
export function clamp(value, min, max);
export function indexOf(string, searchString, start);
export function lastIndexOf(string, searchString, start);
export function substring(string, start, end);
export function length(target);
export function parseNumber(string);
export function parseBoolean(string);
export function push(array, value);
export function pop(array);
export function remove(array, index);
export function insert(array, index, value);
export function shift(array);
export function unshift(array, value);
export function concat(array1, array2);
export function replace(string, substring, replaceValue);
export function replaceAll(string, substring, replaceValue);
export function split(string, splitString);
export function typeOf(value);
export function isNaN(value);
export function keys(object);
export function stringify(value);
export function includes(target, value);
export function combine(object1, object2);
export function getArgument(index);
export function charAt(string, index);
export function timeNow();
